# Generated by Django 5.0.2 on 2024-04-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_remove_usuarios_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='contraseña', max_length=100),
        ),
    ]
