# Generated by Django 5.0.2 on 2024-04-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='dpi',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tel',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
