# Generated by Django 5.0.2 on 2024-04-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_usuarios_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tel',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
