# Generated by Django 5.0.2 on 2024-04-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_usuarios_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tel',
            field=models.CharField(blank=True, null=True),
        ),
    ]
