# Generated by Django 5.0.2 on 2024-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_usuarios_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dpi',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
