# Generated by Django 5.0.2 on 2024-04-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_usuarios_dpi_alter_usuarios_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dpi',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
